<?php

namespace App\Enum;

enum OrderStatusEnum: string
{
    case PLANNED = 'PLANNED';
    case REVIEW = 'REVIEW';
    case CONFIRMED = 'CONFIRMED';
    case DELIVERY_CONFIRMED = 'DELIVERY CONFIRMED';
    case EXECUTION = 'EXECUTION';
    case SUPERVISION = 'SUPERVISION';
    case INSPECTION = 'INSPECTION';
    case FINISH = 'FINISH';
    case FINAL_INSPECTION = 'FINAL INSPECTION';
    case FINAL_COLLECT = 'PENDING COLLECT';
    case ON_HOLD = 'ON HOLD';
    case COMPLETE = 'COMPLETE';
    case RESCHEDULE = 'RESCHEDULED';
    case CONFIRMED_FINISH = 'CONFIRMED FINISH';
    case SERVICE = 'SERVICE';
    case MATERIALS_RECEIVED = 'MATERIALS RECEIVED';
    case NEW_CUSTOMER_REQUEST = 'NEW REQUEST';
    case NEW_CUSTOMER_REQUEST_FOLLOW_UP = 'REQUEST FOLLOW UP';
    case NEW_CUSTOMER_REQUEST_STAND_BY = 'REQUEST STAND BY';
    case LOST_CUSTOMER_REQUEST = 'LOST REQUEST';
    case QUALIFIED = 'QUALIFIED';
    case NEW_CUSTOMER_REQUEST_REVIEW = 'REQUEST REVIEW';

}
