<?php

namespace App\Enum;

enum OrderStatusEnum: string
{
    case PLANNED = 'PLANNED';
    case REVIEW = 'REVIEW';
    case CONFIRMED = 'CONFIRMED';
    case DELIVERY_CONFIRMED = 'DELIVERY CONFIRMED';
    case EXECUTION = 'EXECUTION';
    case SUPERVISION = 'SUPERVISION';
    case INSPECTION = 'INSPECTION';
    case FINISH = 'FINISH';
    case FINAL_INSPECTION = 'FINAL INSPECTION';
    case FINAL_COLLECT = 'PENDING COLLECT';
    case ON_HOLD = 'ON HOLD';
    case COMPLETE = 'COMPLETE';
    case RESCHEDULE = 'RESCHEDULED';
    case CONFIRMED_FINISH = 'CONFIRMED FINISH';
    case SERVICE = 'SERVICE';
    case MATERIALS_RECEIVED = 'MATERIALS RECEIVED';
    case NEW_CUSTOMER_REQUEST = 'NEW REQUEST';
    case NEW_CUSTOMER_REQUEST_FOLLOW_UP = 'REQUEST FOLLOW UP';
    case NEW_CUSTOMER_REQUEST_STAND_BY = 'REQUEST STAND BY';
    case LOST_CUSTOMER_REQUEST = 'LOST REQUEST';
    case QUALIFIED = 'QUALIFIED';
    case NEW_CUSTOMER_REQUEST_REVIEW = 'REQUEST REVIEW';
    case PENDING_ASSIGNMENT = 'PENDING ASSIGNMENT';
    case REQUEST_RE_SCHEDULE = 'REQUEST RE-SCHEDULE';
    case ESTIMATE_APPT_SCHEDULE = 'ESTIMATE APPT SCHEDULE';
    case FOLLOW_UP = 'FOLLOW UP';
    case FOLLOW_UP_PROJECTS = 'FOLLOW UP PROJECTS';
    case STAND_BY = 'STAND BY';
    case COMMERCIAL_ASSIGNMENT = 'COMMERCIAL ASSIGNMENT';
    case PRE_CONTRACT_APPOINTMENT = 'PRE CONTRACT APPOINTMENT';
    case CONTRACT_SIGNED_BY_CLIENT = 'CONTRACT SIGNED BY CLIENT';

}
